src/application/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url

from core.views import test

from core.views import public, protected
from users.views import upload_photo, upload_file
from topics.views import topic_detail, topic_remove, topic_list

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(('core.urls', 'core'), namespace='core')),
    url(r'^user/', include(('users.urls', 'users'), namespace='users')),
    url(r'^topic/', include(('topics.urls', 'topics'), namespace='topics')),
    url(r'^category/', include(('categories.urls', 'categories'), namespace='categories')),

    url(r'^test/$', test),
    url(r'^api/', jsonrpc_site.dispatch),
    url(r'', include('social_django.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.conf.urls import url
from core.views import *

urlpatterns = [

    url(
        r'^login/$',
        login,
        name='login'
    ),

    url(
        r'^logout/$',
        logout,
        name='logout'
    ),

    url(
        r'^register/$',
        register,
        name='register'
    ),

    url(
        r'^feedback/$',
        getFeedback,
        name='feedback'
    ),

    url(
        r'^profile/$',
        profile,
        name='profile'
    ),

    url(
        r'^public/(?P<filename>\w+.\w+)/$',
        public,
        name='public'
    ),
    url(
        r'^protected/(?P<bucket>\w+)/(?P<key>\w+)/$',
        protected,
        name='protected'
    ),
]

src/topics/urls.py
from django.conf.urls import url
from topics.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        r'^list/$',
        topic_list,
        name='list'
    ),

    url(
        r'^add/$',
        topic_add,
        name='add'
    ),

    url(
        r'^(?P<pk>\d+)/edit/$',
        login_required(TopicEdit.as_view()),
        name='edit'
    ),

    url(
        r'^(?P<pk>\d+)/detail/$',
        login_required(topic_detail),
        name='detail'
    ),

    url(
        r'^(?P<pk>\d+)/remove/$',
        login_required(topic_remove),
        name='remove'
    ),

    url(
        r'^(?P<pk>\d+)/detail/comments/$',
        login_required(topic_comments),
        name='comments'
    ),

    url(
        r'^(?P<pk>\d+)/addcomment/(?P<parent_id>\d+)/$',
        login_required(topic_comment_add),
        name='comment_add'
    ),

    url(
        r'^(?P<pk>\d+)/detail/likes/$',
        login_required(likes_counter),
        name='likes'
    ),

    url(
        r'^(?P<pk>\d+)/addlike/$',
        login_required(likes_update),
        name='like_add'
    )
]

src/users/urls.py
from django.conf.urls import url
from users.views import *

urlpatterns = [
    url(
        r'^home/$',
        user_index,
        name='index'
    ),

    url(
        r'^info/$',
        user_info,
        name='info'
    ),

    url(
        r'^get_user/(?P<id>\d+)/$',
        get_user,
        name='get_user'
    ),

    url(
        r'^get_all_users/$',
        get_all_users,
        name='get_all_users'
    ),
]

src/topics/models.py
from django.db import models
from django.conf import settings

from categories.models import Category

class TopicQueryset(models.QuerySet):

    def annotate_everything(self):
        qs = self.select_related("author")
        qs = qs.prefetch_related("categories", "topic_likes", "topic_likes__author")
        #qs = qs.annotate(likes_count=models.Count('topic_likes'))
        return qs

    def get_stats(self):
        return self.aggregate(all_topic_count=models.Count('id'))

class Topic(models.Model):

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='topics',
        verbose_name='Автор топика',
        on_delete = models.CASCADE
    )

    text = models.TextField(
        max_length=40980,
        verbose_name='Текст топика'
    )

    categories = models.ManyToManyField(
        Category,
        related_name='topics',
        verbose_name='Категория'
    )

    name = models.CharField(
        max_length=127,
        verbose_name='Название топика'
    )

    is_archive = models.BooleanField(
        default=False,
        verbose_name='В архиве?'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления'
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано?"
    )

    viewcount = models.IntegerField(
        default=0,
        verbose_name='Просмотры'
    )

    objects = TopicQueryset.as_manager()

    class Meta:
        verbose_name = 'Топик'
        verbose_name_plural = 'Топики'
        ordering = 'name', 'id'

    def __unicode__(self):
        return self.name

src/topics/views.py
import time

from django.http import JsonResponse

from django import forms
from django.db import models
from django.views.generic import CreateView, UpdateView, DetailView
from django.shortcuts import render, get_object_or_404, reverse, HttpResponse, Http404
from django.core.serializers import serialize
from users.models import User
from topics.models import Topic
from likes.models import Like
from django.forms import ModelForm
from comments.models import Comment

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.views.decorators.csrf import csrf_exempt
from jsonrpc import jsonrpc_method
import hashlib, boto3, json

@csrf_exempt
def topic_list(request):
    if request.method == 'GET':
        topics = Topic.objects.all()
        j_topics = []
        for topic in topics:
            j_topics.append({
                'id': topic.id,
                'author_id': topic.author_id,
                'name': topic.name,
                'text': topic.text,
                'categories_id': [entry for entry in topic.categories.values_list('id', flat=True)],
            })
        return JsonResponse(j_topics, safe=False)
    else:
        return Http404('Wrong request method')

@csrf_exempt
def topic_add(request):
    if request.method == 'GET':
        return Http404('Wrong request method')
    elif request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        data['categories'] = [1]
        form = TopicForm(data=data)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.author_id = data['author_id']
            topic.save()
            form.save_m2m()
            publish_topic(topic)
            return JsonResponse({ 'status': 200 })
        else:
            return HttpResponse('Error', status=400)

class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ('name', 'categories', 'text')

import requests, json
from application.settings import CENTRIFUGE_API_KEY

def publish_topic(topic):
    command = {
        "method": "publish",
        "params": {
            "channel": "public:topic",
                "data": {
                    'id': topic.id,
                    'author_id': 1,
                    'name': topic.name,
                    'text': topic.text,
                    'categories_id': [entry for entry in topic.categories.values_list('id', flat=True)],
                }
            }
    }

    api_key = CENTRIFUGE_API_KEY
    data = json.dumps(command)
    print(data)
    headers = {'Content-type': 'application/json', 'Authorization': 'apikey ' + api_key}
    resp = requests.post("http://centrifugo:9000/api", data=data, headers=headers)
    print(resp.json())

@jsonrpc_method('api.topic_detail')
def topic_detail(request, pk=None):

    topic = get_object_or_404(Topic, id=pk)
    form = CommentForm(request.POST)

    if request.method == "GET":
        Topic.objects.filter(id=pk).update(viewcount=models.F('viewcount') + 1)

    elif request.method == "POST":
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.topic_id = pk

            comment.save()
            form = CommentForm()



    context = {
        'topic': topic,
        'comment_form': form,
        'comments': topic.topic_comments.all().filter(is_archive=False).filter(comment=None).order_by('created')
    }

    print(context)

    #return HttpResponse(serialize('json', topic), content_type="application/json")
    return render(request, 'topics/detail.html', context)



@jsonrpc_method('api.topic_remove')
def topic_remove(request, pk=None):

    topic = get_object_or_404(Topic, id=pk, author=request.user)

    context = {
        'topic': topic
    }

    #return HttpResponse(serialize('json', context['topic']), content_type="application/json")
    return render(request, 'topics/remove.html', context)


class TopicsListForm(forms.Form):

    sort = forms.ChoiceField(
        choices=(
            ('name', 'Name asc'),
            ('-name', 'Name desc'),
            ('id', 'By Id'),
            ('created', 'By date'),
        ),
        required=False)
    category = forms.CharField(required=False)
    search = forms.CharField(required=False)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Добавить комментарий'))

class TopicEdit(UpdateView):
    form_class = TopicForm
    model = Topic
    template_name = 'topics/edit.html'
    context_object_name = 'topic'

    def get_queryset(self):
        queryset = super(TopicEdit, self).get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset

    def get_success_url(self):
        return reverse('topics:detail', kwargs={'pk': self.object.pk})


def topic_comments(request, pk=None):

    topic = get_object_or_404(Topic, id=pk)
    context = {
        'comments': topic.topic_comments.all().filter(is_archive=False).filter(comment=None).order_by('created')
    }

    return render(request, 'topics/widgets/comment_all.html', context)

def likes_counter(request, pk=None):

    topic = get_object_or_404(Topic, id=pk)
    context = {
        'count': topic.topic_likes.all().filter(is_archive=False).count()
    }

    return render(request, 'topics/widgets/like_counter.html', context)

def likes_update(request, pk=None):

    topic = get_object_or_404(Topic, id=pk)

    like = None
    if topic.topic_likes.filter(topic=topic, author=request.user).count() == 1:
        like = topic.topic_likes.get(topic=topic, author=request.user)

    if like == None:
        like = Like()
        like.author = request.user
        like.topic = topic
        like.save()
        return HttpResponse("Дизлайк")

    else:
        if like.is_archive:
            like.is_archive = False
            like.save()
            return HttpResponse("Лайк")

        else:
            like.is_archive = True
            like.save()
            return HttpResponse("Дизлайк")


class AddCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(AddCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.add_input(Submit('submit', 'Ответить'))


def topic_comment_add(request, pk=None, parent_id=None):

    topic = get_object_or_404(Topic, id=pk)
    parent_comment = get_object_or_404(Comment, id=parent_id)
    form = AddCommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.topic = topic
        comment.comment = parent_comment
        comment.save()
        return HttpResponse("OK")

    context = {
        'comment_form': form,
        'topic': topic,
        'parent_comment': parent_comment
    }

    return render(request, 'topics/widgets/comment_add.html', context)

def get_200():
    time.sleep(10)
    return 200;

src/topics/templates/topics/add.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block TITLE %} Создание топика - {{ block.super }} {% endblock %}


{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url "users:index" %}">Назад</a></p>
        </div>
    </div>

    <h3>Создание топика</h3>

    {% crispy form %}
{% endblock %}

src/topics/templates/topics/detail.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block TITLE %} Топик - {{ block.super }} {% endblock %}


{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url 'categories:list'%}">Назад</a></p>
        </div>
    </div>

    <div class="float-right">
        <form class="like-form" method="post" data-url="{% url "topics:like_add" pk=topic.id %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-secondary" value="Лайк">
        </form>
    </div>

    <h3>Топик "{{topic.name}}"</h3>
    <div class="row my-2">
        <div class="col-md-12">
            <div class="card mt-1">
                <div class="card-body">
                    <p>{{ topic.text }}</p>
                </div>
            </div>
        </div>
    </div>

    <h3 class="float-right">Счетчик лайков: <span class="autoload" data-url="{% url "topics:likes" pk=topic.id %}"></span></h3>

    <h3>В категориях</h3>
    <div class="row my-2">
        <div class="col-md-12">
            <div class="card mt-1">
                <div class="card-body">
                {% for category in topic.categories.all %}
                    {% if not forloop.first %},{%endif%}
                    <a href="{% url "categories:detail" pk=category.id %}">{{ category.name }}</a>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <h3 class="float-right">Счетчик просмотров: {{ topic.viewcount }}</h3>

    <h3>Комментарии</h3>
    <div class="row my-2">
        <div class="col-md-12">
            <div class="autoload" data-url="{% url "topics:comments" pk=topic.id %}">
            </div>
        </div>
    </div>

    <h3>Ваш комментарий</h3>
    {% crispy comment_form %}

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Ответить</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <form class="ajax-add-comment" method="post" action="">

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/topics/templates/topics/edit.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block TITLE %} Редактирование топика - {{ block.super }} {% endblock %}


{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url "topics:detail" pk=topic.id %}">Назад</a></p>
        </div>
    </div>

    <h3>Редактирование топика</h3>

    {% crispy form %}
{% endblock %}

src/topics/templates/topics/list.html
{% extends "core/base.html" %}

{% block TITLE %}
    This is topic_list
{% endblock %}


{% block CONTENT %}
    <a href="{% url 'users:index' %}">back</a><br>

    <form action="" method="get">
        {{ topics_form }}
        <input type="submit" value="Go">
    </form>

    Topics:<br>
    {% for now_topic in topics %}
        [{{ now_topic.id }}] {{ now_topic.name }} <a href="{% url "topics:detail" pk=now_topic.id %}">link</a><br>
    {% endfor %}
{% endblock %}

src/topics/templates/topics/remove.html
{% extends "core/base.html" %}

{% block TITLE %}Доступ к топику - {{ block.super }} {% endblock %}


{% block CONTENT %}
      <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url 'users:index'%}">Назад</a></p>
        </div>
    </div>

    <h3>Доступ к топику</h3>
{% endblock %}