src/application/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url

from core.views import test

from core.views import public, protected
from users.views import upload_photo, upload_file
from topics.views import topic_detail, topic_remove, topic_list

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(('core.urls', 'core'), namespace='core')),
    url(r'^user/', include(('users.urls', 'users'), namespace='users')),
    url(r'^topic/', include(('topics.urls', 'topics'), namespace='topics')),
    url(r'^category/', include(('categories.urls', 'categories'), namespace='categories')),

    url(r'^test/$', test),
    url(r'^api/', jsonrpc_site.dispatch),
    url(r'', include('social_django.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/categories/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from categories.views import *

urlpatterns = [
    url(
        r'^add/$',
        login_required(category_add),
        name='add'
    ),

    url(
      r'^(?P<pk>\d+)/edit/$',
        login_required(category_edit),
        name='edit'
    ),

    url(
        r'^list/$',
        category_list,
        name='list'
    ),

    url(
        r'^(?P<pk>\d+)/remove/$',
        login_required(category_remove),
        name='remove'
    ),

    url(
        r'^(?P<pk>\d+)/detail/$',
        login_required(category_detail),
        name='detail'
    ),
]

src/core/urls.py
from django.conf.urls import url
from core.views import *

urlpatterns = [

    url(
        r'^login/$',
        login,
        name='login'
    ),

    url(
        r'^logout/$',
        logout,
        name='logout'
    ),

    url(
        r'^register/$',
        register,
        name='register'
    ),

    url(
        r'^feedback/$',
        getFeedback,
        name='feedback'
    ),

    url(
        r'^profile/$',
        profile,
        name='profile'
    ),

    url(
        r'^public/(?P<filename>\w+.\w+)/$',
        public,
        name='public'
    ),
    url(
        r'^protected/(?P<bucket>\w+)/(?P<key>\w+)/$',
        protected,
        name='protected'
    ),
]

src/users/urls.py
from django.conf.urls import url
from users.views import *

urlpatterns = [
    url(
        r'^home/$',
        user_index,
        name='index'
    ),

    url(
        r'^info/$',
        user_info,
        name='info'
    ),

    url(
        r'^get_user/(?P<id>\d+)/$',
        get_user,
        name='get_user'
    ),

    url(
        r'^get_all_users/$',
        get_all_users,
        name='get_all_users'
    ),
]

src/categories/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(
        max_length=127,
        verbose_name='Тема категории'
    )

    description = models.TextField(
        max_length=4096,
        verbose_name='Описание категории'
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )

    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления'
    )

    is_hidden = models.BooleanField(
        default=False,
        verbose_name='Категория скрыта?'
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = 'name', 'id'

    def __unicode__(self):
        return self.name

src/categories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from django.http import Http404, JsonResponse
from .models import Category
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.cache import caches
from likes.models import Like
from django.db.models import Q
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
cache = caches['default']


@csrf_exempt
def category_list(request):
    categories = Category.objects.all()

    j_categories = []
    for category in categories:
        j_categories.append({
            'id': category.id,
            'name': category.name,
            'description': category.description,
            'topics_id': [entry for entry in category.topics.values_list('id', flat=True)],
        })

    return JsonResponse(j_categories, safe=False)

def category_detail(request, pk=None):
    category = get_object_or_404(Category, id=pk)
    topics = category.topics.all().filter(is_archive=False)

    topics = topics.annotate_everything()

    for topic in topics:
        cache_key = 'post{}likescount'.format(topic.id)
        likes_count = cache.get(cache_key)

        if likes_count is None:
            likes_count = Like.objects.filter(Q(topic=topic)&Q(is_archive=False)).count()
            cache.set(cache_key, likes_count, 10)
        topic.likes_count = likes_count

    form = TopicSortForm(request.GET)
    if form.is_valid():
        data = form.cleaned_data

        if data['sort']:
            topics = topics.order_by(data['sort'])

        if data['search']:
            topics = topics.filter(name__icontains=data['search'])

    context = {
        'category': category,
        'topics': topics,
        'topics_form': form,
    }

    return render(request, 'categories/detail.html', context)


def category_edit(request, pk=None):
    if not request.user.is_superuser:
        return Http404()

    category = get_object_or_404(Category, id=pk)

    context = {
        'category': category,
    }

    if request.method == 'GET':
        form = CategoryForm(instance=category)
        context['category_form'] = form
        return render(request, 'categories/edit.html', context)

    elif request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        context['category_form'] = form
        if form.is_valid():
            form.save()
            return redirect('categories:list')
        else:
            return render(request, 'categories/add.html', {'category_form': form})


def category_add(request):
    if not request.user.is_superuser:
        return Http404()

    if request.method == 'GET':
        form = CategoryForm()
        return render(request, 'categories/add.html', {'category_form': form})

    elif request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            publish_category(category)
            return redirect('categories:detail', pk=category.id)
        else:
            return render(request, 'categories/add.html', {'category_form': form})

import requests, json
from application.settings import CENTRIFUGE_API_KEY

def publish_category(category):
    command = {
        "method": "publish",
        "params": {
            "channel": "public:screen-updates",
                "data": {
                    "category": serialize('json', [ category, ], )
                }
            }
    }

    api_key = CENTRIFUGE_API_KEY
    data = json.dumps(command)
    headers = {'Content-type': 'application/json', 'Authorization': 'apikey ' + api_key}
    resp = requests.post("http://centrifugo:9000/api", data=data, headers=headers)
    print(resp.json())

def category_remove(request, pk=None):

    if not request.user.is_superuser:
        return Http404()

    category = get_object_or_404(Category, id=pk)

    context = {
        'category': category
    }
    return render(request, 'categories/remove.html', context)



class CategorySortForm(forms.Form):

    sort = forms.ChoiceField(
        choices=(
            ('name', 'По теме'),
            ('-likes_count', 'По рейтингу'),
            ('id', 'По ID'),
            ('-created', 'По дате создания'),
        ),
        required=False
    )

    search = forms.CharField(
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(CategorySortForm, self).__init__(*args, **kwargs)
        self.fields['sort'].widget.attrs['class'] = 'form-control'
        self.fields['search'].widget.attrs['class'] = 'form-control'

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить'))

class TopicSortForm(forms.Form):

    sort = forms.ChoiceField(
        choices=(
            ('name', 'По имени'),
            ('-likes_count', 'По рейтингу'),
            ('id', 'По ID'),
            ('-created', 'По дате создания'),
        ),
        required=False)
    search = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(TopicSortForm, self).__init__(*args, **kwargs)
        self.fields['sort'].widget.attrs['class'] = 'form-control'
        self.fields['search'].widget.attrs['class'] = 'form-control'

src/categories/templates/categories/add.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block TITLE %} Создание категории - {{ block.super }} {% endblock %}


{% block CONTENT %}
    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url "categories:list" %}">Назад</a></p>
        </div>
    </div>

    <h3>Создание категории</h3>

    {% crispy category_form %}

{% endblock %}

src/categories/templates/categories/detail.html
{% extends "core/base.html" %}
{% load cache %}

{% block TITLE %} Категория - {{ block.super }} {% endblock %}


{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url 'categories:list'%}">Назад</a></p>
        </div>
    </div>

    <h3>Категория "{{category.name}}" (всего {{ topics.get_stats.all_topic_count }} топиков)</h3>
    <div class="row my-2">
        <div class="col-md-12">
            <div class="card mt-1">
                <div class="card-body">
                    <p>{{ category.description }}</p>
                </div>
            </div>
        </div>
    </div>

    <a class="btn btn-primary float-right" href="{% url "topics:add" %}" role="button">Добавить топик</a>

    <h3>Топики</h3>

    <div class="row mb-2">
        <form action="" method="get">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="col">
                        {{ topics_form.sort }}
                    </div>
                    <div class="col">
                        {{ topics_form.search }}
                    </div>
                    <div class="col">
                        <input class="btn btn-secondary" type="submit" value="Поиск">
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="row">
        {% for topic in topics %}
            <div class="col-md-12">
                <div class="card mt-1">
                    <div class="card-body">
                        <a class="card-link" href="{% url "topics:detail" pk=topic.id %}">{{ topic.name }}</a>
                        <hr>
                        <div>
                            Автор: <i>{{ topic.author.username }}</i>
                        </div>

                        <div>
                            В категориях:
                            {% for now_category in topic.categories.all %}
                                {% if not forloop.first %},{%endif%}
                                <i><a href="{% url "categories:detail" pk=now_category.id %}">{{ now_category.name }}</a></i>
                            {% endfor %}
                        </div>
                        <hr>
                        <div>
                            Понравилось ({{ topic.likes_count }}):
                            {% for like in topic.topic_likes.all %}
                                {% if not like.is_archive %}
                                    <i>{{ like.author.username }}</i>
                                    {% if not forloop.last %},{%endif%}
                                {% endif %}
                            {% empty %}
                                пока никому
                            {% endfor %}
                        </div>
                        <div>
                            Посмотрело {% cache 5 "viewcount" topic.id %} {{ topic.viewcount }} {% endcache %} человек
                        </div>
                        {% if user.is_superuser or topic.author == user %}
                            {% if category.is_hidden %}
                                <div class="card-link float-right"><a href="{% url 'topics:remove' pk=category.id %}">Открыть</a></div><br>
                            {% else %}
                                <div class="card-link float-right"><a href="{% url 'topics:remove' pk=category.id %}">Скрыть</a></div><br>
                            {% endif %}
                            <div class="card-link float-right"><a href="{% url 'topics:edit' pk=category.id %}">Редактировать</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">Нет ни одного топика в категории</div>
        {% endfor %}
    </div>
{% endblock %}

src/categories/templates/categories/edit.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block TITLE %} Редактирование категории - {{ block.super }} {% endblock %}


{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url "categories:detail" pk=category.id %}">Назад</a></p>
        </div>
    </div>

    <h3>Редактирование категории</h3>

    {% crispy category_form %}
{% endblock %}

src/categories/templates/categories/list.html
{% extends "core/base.html" %}

{% block TITLE %} Категории - {{ block.super }} {% endblock %}

{% block CUSTOME_SCRIPTS %}
    <script src="//cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js" type="text/javascript"></script>
    <script src="https://rawgit.com/centrifugal/centrifuge-js/c2/dist/centrifuge.min.js"></script>
{% endblock %}

{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url "users:index" %}">Назад</a></p>
        </div>
    </div>

    {% if user.is_superuser %}
        <a class="btn btn-primary float-right" href="{% url "categories:add" %}" role="button">Добавить категорию</a>
    {% endif %}

    <h3>Категории</h3>

    <div class="row mb-2">
        <form action="" method="get">
            <div class="col-md-12">
                <div class="form-row">
                    <div class="col">
                        {{ categories_form.sort }}
                    </div>
                    <div class="col">
                        {{ categories_form.search }}
                    </div>
                    <div class="col">
                        <input class="btn btn-secondary" type="submit" value="Поиск">
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="row categories">
        {% for category in categories %}
            <div class="col-md-12">
                <div class="card mt-1">
                    <div class="card-body">
                        <a class="card-link" href="{% url "categories:detail" pk=category.id %}">{{ category.name }}</a>
                        <p>{{ category.description }}</p>
                        {% if user.is_superuser %}
                            {% if category.is_hidden %}
                                <div class="card-link float-right"><a href="{% url 'categories:remove' pk=category.id %}">Открыть</a></div><br>
                            {% else %}
                                <div class="card-link float-right"><a href="{% url 'categories:remove' pk=category.id %}">Скрыть</a></div><br>
                            {% endif %}
                            <div class="card-link float-right"><a href="{% url 'categories:edit' pk=category.id %}">Редактировать</a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">Категории пока пусты</div>
        {% endfor %}
    </div>

    <script type="text/javascript">
      var centrifuge = new Centrifuge('{{ CENTRIFUGE_SOCKJS_ENDPOINT }}', { debug: true });
      centrifuge.setToken('{{ CENTRIFUGE_TOKEN }}');

      var channel = 'public:screen-updates';
      var subscription = centrifuge.subscribe(channel, function(message) {
        const category = JSON.parse(message.data.category);
        const category_id = category[0].pk;
        const category_data = category[0].fields;

        const category_div =
        `<div class="col-md-12">
            <div class="card mt-1">
                <div class="card-body">
                    <a class="card-link" href="/categories/${ category_id }/detail">${ category_data.name }</a>
                    <p>${ category_data.description }</p>
                    {% if user.is_superuser %}
                        <div class="card-link float-right"><a href="/categories/${ category_id }/remove">Скрыть</a></div><br>
                        <div class="card-link float-right"><a href="/categories/${ category_id }/edit">Редактировать</a></div>
                    {% endif %}
                 </div>
            </div>
        </div>`;
        var category_list = document.body.querySelector('.categories');
        category_list.innerHTML += category_div;
      });

      centrifuge.on('connect', function(context) {
        console.log('connected');
      });

      subscription.on('subscribe', function() {
        console.log("subscribed");
      });

      subscription.on('error', function(err) {
        console.log("error subscribing", err);
      });

      subscription.on('join', function(message) {
        console.log(message);
      });

      subscription.on('leave', function(message) {
        console.log(message);
      });

      centrifuge.connect();
    </script>
{% endblock %}

src/categories/templates/categories/remove.html
{% extends "core/base.html" %}

{% block TITLE %} Доступ к категории - {{ block.super }} {% endblock %}

{% block CONTENT %}

    <div class="row mt-2">
        <div class="col-md-12">
            <p class="card card-block bg-faded"><a href="{% url 'catgeories:list'%}">Назад</a></p>
        </div>
    </div>

    <h3>Доступ к категории</h3>

{% endblock %}