src/application/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url

from core.views import test

from core.views import public, protected
from users.views import upload_photo, upload_file
from topics.views import topic_detail, topic_remove, topic_list

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(('core.urls', 'core'), namespace='core')),
    url(r'^user/', include(('users.urls', 'users'), namespace='users')),
    url(r'^topic/', include(('topics.urls', 'topics'), namespace='topics')),
    url(r'^category/', include(('categories.urls', 'categories'), namespace='categories')),

    url(r'^test/$', test),
    url(r'^api/', jsonrpc_site.dispatch),
    url(r'', include('social_django.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/core/urls.py
from django.conf.urls import url
from core.views import *

urlpatterns = [

    url(
        r'^login/$',
        login,
        name='login'
    ),

    url(
        r'^logout/$',
        logout,
        name='logout'
    ),

    url(
        r'^register/$',
        register,
        name='register'
    ),

    url(
        r'^feedback/$',
        getFeedback,
        name='feedback'
    ),

    url(
        r'^profile/$',
        profile,
        name='profile'
    ),

    url(
        r'^public/(?P<filename>\w+.\w+)/$',
        public,
        name='public'
    ),
    url(
        r'^protected/(?P<bucket>\w+)/(?P<key>\w+)/$',
        protected,
        name='protected'
    ),
]

src/users/urls.py
from django.conf.urls import url
from users.views import *

urlpatterns = [
    url(
        r'^home/$',
        user_index,
        name='index'
    ),

    url(
        r'^info/$',
        user_info,
        name='info'
    ),

    url(
        r'^get_user/(?P<id>\d+)/$',
        get_user,
        name='get_user'
    ),

    url(
        r'^get_all_users/$',
        get_all_users,
        name='get_all_users'
    ),
]

src/core/models.py
from django.db import models

from users.models import User


class File(models.Model):
    name = models.CharField( max_length=32, default='unnamed_file' )
    mime = models.CharField( max_length=72 )
    key = models.CharField( max_length=72 )
    content = models.FileField( null=True, upload_to='files' )
    owners = models.ManyToManyField( User, related_name='files' )

class Feedback(models.Model):
    description = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    issue = models.CharField(max_length=100)

src/core/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect, JsonResponse, Http404, HttpResponse

from application import settings

from django.middleware.csrf import get_token

from users.models import User
from core.models import File, Feedback
from django.forms import ModelForm

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as loginUser, logout as logoutUser

from django.views.decorators.csrf import csrf_exempt

from jsonrpc import jsonrpc_method
import hashlib, boto3, json


@csrf_exempt
def login(request):
    if request.method == 'GET':
        return Http404('Wrong request method')
    elif request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        form = AuthenticationForm(data=data)
        if form.is_valid():
            user = form.get_user()
            loginUser(request, user)
            return JsonResponse({
                'userId': user.pk,
                'token': generate_key(user.get_username())
            })
        else:
            return HttpResponse('Unauthorized', status=401)


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

@csrf_exempt
def register(request):
    if request.method == 'GET':
        return Http404('Wrong request method')
    elif request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        form = RegistrationForm(data=data)
        if form.is_valid():
            form.save()
            return JsonResponse({ 'status': 200 })
        else:
            return HttpResponse('Registration error', status=401)

@csrf_exempt
def logout(request):
    logoutUser(request)
    return JsonResponse({ 'status': 200 })

def test(request):
    if request.method == 'GET':
        return JsonResponse({ 'csrfmiddlewaretoken': get_token(request)})
    elif request.method == 'POST':
        return JsonResponse({ 'status': 'OK'})

@jsonrpc_method( 'api.public' )
def public(request, filename):
    key = generate_key(filename)
    file = File.objects.filter(key=key, owners=1).first()

    if file is None:
        return HttpResponseNotFound('404')

    else:
        return HttpResponseRedirect('/protected/{}/{}/'.format(settings.AWS_STORAGE_BUCKET_NAME, key))


@jsonrpc_method( 'api.protected' )
def protected(request, bucket, key):

    session = boto3.session.Session()
    s3_client = session.client(
        service_name='s3',
        endpoint_url=settings.AWS_S3_ENDPOINT_URL,
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
    )

    url = s3_client.generate_presigned_url(
        'get_object',
        Params={
            'Bucket': bucket,
            'Key': 'files/1/{}'.format(key),
        }
    )

    return JsonResponse({ 'url': url })


def generate_key(filename):
    h = hashlib.new('md5')
    h.update(filename.encode('utf-8'))
    return h.hexdigest()

@csrf_exempt
def getFeedback(request):
    if request.method == 'GET':
        return Http404('Wrong request method')

    elif request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        form = FeedbackForm(data=data)
        if form.is_valid():
            feedback = form.save()
            print(feedback)
            return JsonResponse({'status': 200})

        print('Feedback received:\n{}'.format(data))
        return JsonResponse({ 'status': 200 })

@csrf_exempt
def profile(request):
    if request.method == 'GET':
        return Http404('Wrong request method')

    elif request.method == 'POST':
        # data = json.loads(request.body.decode('utf-8'))
        # print('User profile received:\n{}'.format(data))
        return JsonResponse({'status': 200})


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ('description', 'username', 'issue')

src/core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "bootstrap-4.1.0/favicon.ico" %}">

    <title> {% block TITLE %}MIPT Overflow{% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap-4.1.0/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    {% block CUSTOME_STYLES %}{% endblock %}
    {% block CUSTOME_SCRIPTS %}{% endblock %}
    <link href="{% static "bootstrap-4.1.0/docs/4.1/examples/sticky-footer-navbar/sticky-footer-navbar.css" %}" rel="stylesheet">
    <link href="{% static "chosen/bootstrap-chosen.css" %}" rel="stylesheet">
  </head>

  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <a class="navbar-brand" href="#">Mipt Overflow</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav ml-auto">
                  {% if user.is_authenticated  %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "users:index" %}">{{ user.first_name }} {{ user.last_name }} [{{ user.username }}]</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:logout" %}">Выйти</a>
                      </li>
                  {% else %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:login" %}">Войти</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url "core:register" %}">Зарегестрироваться</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
        {% block CONTENT %}
            Default content
        {% endblock %}
    </main>

    <footer class="footer">
        {% block FOOTER %}
        <div class="container">
            <span class="text-muted">@Copyleft Morev Maxim Company 2018.</span>
        </div>
        {% endblock %}
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "bootstrap-4.1.0/assets/js/vendor/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "bootstrap-4.1.0/assets/js/vendor/popper.min.js" %}"></script>
    <script src="{% static "bootstrap-4.1.0/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "my_scripts.js" %}"></script>
    <script src="http://harvesthq.github.io/chosen/chosen.jquery.js"></script>
  </body>
</html>

src/core/templates/core/index.html
{% extends "core/base.html" %}

{% block CONTENT %}
    <h1 class="mt-2">Hi! It's my Mipt Overflow!</h1>
    <a href="/user/home/">/user/home/</a>
{% endblock %}

src/core/templates/core/login.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block TITLE %} Login - {{ block.super }}{% endblock %}

{% block CUSTOME_STYLES %}
    <link href="{% static "bootstrap-4.1.0/docs/4.1/examples/sign-in/signin.css" %}" rel="stylesheet">
{% endblock %}

{% block CONTENT %}
    <form class="form-signin" action="" method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
    <div class="text-black-50 text-md-center">
        Don't have an account?
        <a href="{% url "core:register" %}">Sign up</a>
    </div>
    <div class="text-black-50 text-md-center">
        Login with
        <a href="/login/vk-oauth2/">VK</a>
        <a href="/login/github/">Github</a>
    </div>
{% endblock %}

src/core/templates/core/register.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block TITLE %} Signup - {{ block.super }} {% endblock %}

{% block CONTENT %}
    <div class="row">
        <div class="col-6">
            <h1 class="mt-2">Registration</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}